version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev
    
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    networks:
      - dev
  www:
    build: php
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
  angular:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    command: >
      sh -c "npm install -g @angular/cli@latest &&
             npm install &&
             ng serve --host 0.0.0.0 --poll=2000  || tail -f /dev/null"
    networks:
      - dev
volumes:
  db-data:

networks:
  dev:
